version: '2'

services:
  wazuh:
    build: wazuh/
    ports:
      - "1514/udp:1514/udp"
      - "1515:1515"
      - "514/udp:514/udp"
      - "55000:55000"
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
